default:
  #SQLITE
  engine:   "sqlite"
  database: "db.sqlite"
  #MYSQL
  #engine:   "mysql"
  #host:     "db_hostname"
  #database: "db_name"
  #user:     "db_username"
  #password: "db_password"

  backtest:
    sma_period:
      min:  100
      max:  800
    upper_band:
      min:  0.8
      max:  2.5
    lower_band:
      min:  -2.5
      max:  -0.8
    up_change:
      min:  0
      max:  8
    down_change:
      min:  -8
      max:  0
    low_limit:
      min: 0
      max: 0.8
    stop_loss:
      min: 0
      max: 0.5
    stop_gain:
      min: 1.05
      max: 2
    bear_sell:
      min:  0
      max:  0.8
    bear_buy:
      min:  0.2
      max:  1.0
    bull_sell:
      min:  0.2
      max:  1.0
    bull_buy:
      min:  0
      max:  0.8

  alert:
    type:         "none"
    target:       ""
    #type:         "email"
    #target:       "user@domain"
    #type:         "s3"
    #target:       "s3_bucket_name"
    #baseurl:      "s3_bucket_url"
    
aws:
  engine:   "mysql"
  host:     "db_hostname"
  database: "db_name"
  user:     "db_username"
  password: "db_password"
  alert:
    type:         "s3"
    target:       "s3_bucket_name"
    baseurl:      "s3_bucket_url"
