default:
  #SQLITE
  engine:   "sqlite"
  database: "db.sqlite"
  #MYSQL
  #engine:   "mysql"
  #host:     "db_hostname"
  #database: "db_name"
  #user:     "db_username"
  #password: "db_password"

  backtest:
    sma_period:
      min:  100
      max:  800
    upper_band:
      min:  1.0
      max:  1.5
    lower_band:
      min:  -1.5
      max:  -1.0
    up_change:
      min:  0.0
      max:  1.0
    down_change:
      min:  -1.0
      max:  0.0
    low_limit:
      min: 0.0
      max: 1.0
    stop_loss:
      min: 0.0
      max: 1.0
    stop_gain:
      min: 1.02
      max: 5.00
    bear_sell:
      min:  0.0
      max:  1.0
    bear_buy:
      min:  0.0
      max:  1.0
    bull_sell:
      min:  0.0
      max:  1.0
    bull_buy:
      min:  0.0
      max:  1.0

  alert:
    type:         "none"
    target:       ""
    #type:         "email"
    #target:       "user@domain"
    #type:         "s3"
    #target:       "s3_bucket_name"
    #baseurl:      "s3_bucket_url"

desktop:
  engine:   "mysql"
  host:     "db_hostname"
  database: "db_name"
  user:     "db_username"
  password: "db_password"

aws:
  engine:   "mysql"
  host:     "db_hostname"
  database: "db_name"
  user:     "db_username"
  password: "db_password"
  alert:
    type:         "s3"
    target:       "s3_bucket_name"
    baseurl:      "s3_bucket_url"
