default:
  #engine:   "sqlite"
  #host:     "db_hostname"
  #database: "db.sqlite"
  #user:     "db_username"
  #password: "db_password"

  backtest:
    sma_period:
      min:  100
      max:  500
    upper_band:
      min:  0.6
      max:  2.5
    lower_band:
      min:  -0.6
      max:  -2.5
    up_change:
      min:  0
      max:  8
    down_change:
      min:  -8
      max:  0
    bull_min:
      min:  0
      max:  0.8
    bull_max:
      min:  0.2
      max:  1.0
    bear_min:
      min:  0
      max:  0.8
    bear_max:
      min:  0.2
      max:  1.0

  trade:
    sma_period:   400
    upper_band:   1.3
    lower_band:   -1.3
    up_change:    5.5
    down_change:  -5.5
    bull_buy:     0.15
    bull_sell:    0.7
    bear_sell:    0
    bear_buy:     0.75

  alert:
    type:         "mail"
    target:       "email_address"

aws:
  engine:   "mysql"
  host:     "db_hostname"
  database: "db_name"
  user:     "db_username"
  password: "db_password"
  alert:
    type:         "s3"
    target:       "s3_bucket_name"
