default:
  #SQLITE
  #engine:   "sqlite"
  #database: "db.sqlite"
  #MYSQL
  #engine:   "mysql"
  #host:     "db_hostname"
  #database: "db_name"
  #user:     "db_username"
  #password: "db_password"

  parameters: "tradeParameters.csv"

  backtest:
    sma_period:
      min:  100
      max:  600
    upper_band:
      min:  1.5
      max:  2.5
    lower_band:
      min:  -2.5
      max:  -1.5
    up_change:
      min:  0.0
      max:  1.0
    down_change:
      min:  -1.0
      max:  0.0
    low_limit:
      min: 0.0
      max: 1.0
    high_limit:
      min: 1.0
      max: 2.0
    stop_loss:
      min: 0.0
      max: 0.98
    stop_gain_long:
      min: 1.01
      max: 2.0
    stop_gain_short:
      min: 1.01
      max: 1.50
    bear_sell:
      min:  0.0
      max:  1.0
    bear_buy:
      min:  0.0
      max:  1.0
    bull_sell:
      min:  0.2
      max:  1.0
    bull_buy:
      min:  0.0
      max:  1.0

  alert:
    type:       "none"
    target:     ""
    #type:      "email"
    #target:    "user@domain"
    #type:      "s3"
    #target:    "s3_bucket_name"
    #baseurl:   "s3_bucket_url"

desktop:
  engine:       !expr config::get("engine", file = "custom-config.yml")
  host:         !expr config::get("host", file = "custom-config.yml")
  database:     !expr config::get("database", file = "custom-config.yml")
  user:         !expr config::get("user", file = "custom-config.yml")
  password:     !expr config::get("password", file = "custom-config.yml")
  parameters:   !expr config::get("parameters", file = "custom-config.yml")

aws:
  engine:       !expr config::get("engine", file = "custom-config.yml")
  host:         !expr config::get("host", file = "custom-config.yml")
  database:     !expr config::get("database", file = "custom-config.yml")
  user:         !expr config::get("user", file = "custom-config.yml")
  password:     !expr config::get("password", file = "custom-config.yml")
  parameters:   !expr config::get("parameters", file = "custom-config.yml")
