default:
  engine:   "sqlite"
  database: "db.sqlite"
  trade:
    sma_period:   400
    upper_band:   1.3
    lower_band:   -1.3
    up_change:    5.5
    down_change:  -5.5
    bull_min:     0.3
    bear_min:     0.2
  alert:
    type:         "mail"
    target:       "email_address"

aws:
  engine:   "mysql"
  host:     "db_hostname"
  database: "db_name"
  user:     "db_username"
  password: "db_password"
  alert:
    type:         "s3"
    target:       "s3_bucket_name"
